services:
    web:
        environment:
            - EXTENSION_KEY=nr_textdb
            - PACKAGE_NAME=netresearch/nr-textdb

            # TYPO3 v13 config
            - TYPO3_DB_DRIVER=mysqli
            - TYPO3_DB_USERNAME=root
            - TYPO3_DB_PASSWORD=root
            - TYPO3_DB_HOST=db
            - TYPO3_SETUP_ADMIN_EMAIL=admin@example.com
            - TYPO3_SETUP_ADMIN_USERNAME=admin
            - TYPO3_SETUP_ADMIN_PASSWORD=Password:joh316
            - TYPO3_PROJECT_NAME=EXT:nr_textdb Dev Environment
            - TYPO3_SERVER_TYPE=apache
        volumes:
            - type: bind
              source: ../
              target: /var/www/nr_textdb
              consistency: cached
            - v13-data:/var/www/html/v13
volumes:
    v13-data:
        name: "${DDEV_SITENAME}-v13-data"
